package tp1;

import java.util.ArrayList;
import java.util.Random;

public class Mapa {

	/*
	 * Método preencher: esse método tem como objetivo, preencher todas as salas com todas as informações possíveis,
	 * 					 como: portas - nomes e trancada ou não, ouro, diamante, poções, chaves e machados.
	 */
	public void preencher(ArrayList<Salas> listasala) {

		Salas sala = new Salas();
		Porta porta = new Porta();
		Porta porta2 = new Porta();
		Salas sala2 = new Salas();
		Porta porta3 = new Porta();
		Porta porta4 = new Porta();
		Salas sala3 = new Salas();
		Porta porta5 = new Porta();
		Porta porta6 = new Porta();
		Salas sala4 = new Salas();
		Porta porta7 = new Porta();
		Porta porta8 = new Porta();
		Salas sala5 = new Salas();
		Porta porta9 = new Porta();
		Porta porta10 = new Porta();
		Salas sala6 = new Salas();
		Porta porta11 = new Porta();
		Porta porta12 = new Porta();
		Salas sala7 = new Salas();
		Porta porta13 = new Porta();
		Porta porta14 = new Porta();
		Salas sala8 = new Salas();
		Porta porta15 = new Porta();
		Porta porta16 = new Porta();
		Salas sala9 = new Salas();
		Porta porta17 = new Porta();
		Salas sala10 = new Salas();
		Porta porta19 = new Porta();
		Porta porta20 = new Porta();
		Porta porta21 = new Porta();
		Salas sala11 = new Salas();
		Porta porta22 = new Porta();
		Porta porta23 = new Porta();
		Salas sala12 = new Salas();
		Porta porta24 = new Porta();
		Porta porta25 = new Porta();
		Salas sala13 = new Salas();
		Porta porta26 = new Porta();
		Porta porta27 = new Porta();
		Salas sala14 = new Salas();
		Porta porta28 = new Porta();
		Porta porta29 = new Porta();
		Salas sala15 = new Salas();
		Porta porta30 = new Porta();
		Porta porta31 = new Porta();
		Salas sala16 = new Salas();
		Porta porta32 = new Porta();
		Porta porta33 = new Porta();
		Salas sala17 = new Salas();
		Porta porta34 = new Porta();
		Porta porta35 = new Porta();
		Salas sala18 = new Salas();
		Porta porta36 = new Porta();
		Porta porta37 = new Porta();
		Salas sala19 = new Salas();
		Porta porta38 = new Porta();
		Porta porta39 = new Porta();
		Salas sala20 = new Salas();
		Porta porta40 = new Porta();
		Porta porta41 = new Porta();
		Porta porta42 = new Porta();
		Item gold = new Item();
		Item gold2 = new Item();
		Item gold3 = new Item();
		Item gold4 = new Item();
		Item gold5 = new Item();
		Item gold6 = new Item();
		Item gold7 = new Item();
		Item gold8 = new Item();
		Item gold9 = new Item();
		Item gold10 = new Item();
		Item gold11 = new Item();
		Item gold12 = new Item();
		Item gold13 = new Item();
		Item gold14 = new Item();
		Item gold15 = new Item();
		Item gold16 = new Item();
		Item gold17 = new Item();
		Item gold18 = new Item();
		Item gold19 = new Item();
		Item gold20 = new Item();
		Item diamante = new Item();
		Item diamante2 = new Item();
		Item diamante3 = new Item();
		Item diamante4 = new Item();
		Item diamante5 = new Item();
		Item diamante6 = new Item();
		Item diamante7 = new Item();
		Item diamante8 = new Item();
		Item diamante9 = new Item();
		Item diamante10 = new Item();
		Item diamante11 = new Item();
		Item diamante12 = new Item();
		Item diamante13 = new Item();
		Item diamante14 = new Item();
		Item diamante15 = new Item();
		Item diamante16 = new Item();
		Item diamante17 = new Item();
		Item diamante18 = new Item();
		Item diamante19 = new Item();
		Item diamante20 = new Item();
		Item pocao = new Item();
		Item pocao2 = new Item();
		Item pocao3 = new Item();
		Item pocao4 = new Item();
		Item pocao5 = new Item();
		Item pocao6 = new Item();
		Item pocao7 = new Item();
		Item pocao8 = new Item();
		Item pocao9 = new Item();
		Item pocao10 = new Item();
		Item pocao11 = new Item();
		Item pocao12 = new Item();
		Item pocao13 = new Item();
		Item pocao14 = new Item();
		Item pocao15 = new Item();
		Item pocao16 = new Item();
		Item pocao17 = new Item();
		Item pocao18 = new Item();
		Item pocao19 = new Item();
		Item pocao20 = new Item();
		Item chave = new Item();
		Item chave2 = new Item();
		Item chave3 = new Item();
		Item chave4 = new Item();
		Item chave5 = new Item();
		Item chave6 = new Item();
		Item chave7 = new Item();
		Item chave8 = new Item();
		Item chave9 = new Item();
		Item chave10 = new Item();
		Item chave11 = new Item();
		Item chave12 = new Item();
		Item chave13 = new Item();
		Item chave14 = new Item();
		Item chave15 = new Item();
		Item chave16 = new Item();
		Item chave17 = new Item();
		Item chave18 = new Item();
		Item chave19 = new Item();
		Item chave20 = new Item();
		Item machado = new Item();
		Item machado2 = new Item();
		Item machado3 = new Item();
		Item machado4 = new Item();
		Item machado5 = new Item();
		Item machado6 = new Item();
		Item machado7 = new Item();
		Item machado8 = new Item();
		Item machado9 = new Item();
		Item machado10 = new Item();
		Item machado11 = new Item();
		Item machado12 = new Item();
		Item machado13 = new Item();
		Item machado14 = new Item();
		Item machado15 = new Item();
		Item machado16 = new Item();
		Item machado17 = new Item();
		Item machado18 = new Item();
		Item machado19 = new Item();
		Item machado20 = new Item();

		sala.setNome(1);
		porta.setNome("A");
		porta.setEntrada(1);
		porta.setSaida(6);
		porta.setTrancada(0);
		sala.getPortas().add(porta);
		porta2.setNome("B");
		porta2.setEntrada(1);
		porta2.setSaida(2);
		porta2.setTrancada(0);
		sala.getPortas().add(porta2);
		gold.setRandomOuro(2, 5);
		sala.getItens().add(gold);
		diamante.setRandomDiamante(2, 5);
		sala.getItens().add(diamante);
		pocao.setRandomPocao(0, 1);
		sala.getItens().add(pocao);
		chave.setChave(0);
		sala.getItens().add(chave);
		machado.setRandomMachado(0, 1);
		sala.getItens().add(machado);
		listasala.add(0, sala);

		sala2.setNome(2);
		porta3.setNome("A");
		porta3.setEntrada(2);
		porta3.setSaida(1);
		porta3.setTrancada(0);
		sala2.getPortas().add(porta3);
		porta4.setNome("B");
		porta4.setEntrada(2);
		porta4.setSaida(3);
		porta4.setTrancada(0);
		sala2.getPortas().add(porta4);
		gold2.setRandomOuro(2, 5);
		sala2.getItens().add(gold2);
		diamante2.setRandomDiamante(2,5);
		sala2.getItens().add(diamante2);
		pocao.setRandomPocao(0, 1);
		sala2.getItens().add(pocao2);
		chave2.setChave(0);
		sala2.getItens().add(chave2);
		machado2.setRandomMachado(0, 1);
		sala2.getItens().add(machado2);
		listasala.add(1, sala2);

		sala3.setNome(3);
		porta5.setNome("A");
		porta5.setEntrada(3);
		porta5.setSaida(2);
		porta5.setTrancada(0);
		sala3.getPortas().add(porta5);
		porta6.setNome("B");
		porta6.setEntrada(3);
		porta6.setSaida(8);
		porta6.setTrancada(0);
		sala3.getPortas().add(porta6);
		gold3.setRandomOuro(2, 5);
		sala3.getItens().add(gold3);
		diamante3.setRandomDiamante(2,5);
		sala3.getItens().add(diamante3);
		pocao3.setRandomPocao(0, 1);
		sala3.getItens().add(pocao3);
		chave3.setChave(0);
		sala3.getItens().add(chave3);
		machado3.setRandomMachado(0, 1);
		sala3.getItens().add(machado3);
		listasala.add(2, sala3);

		sala4.setNome(4);
		porta7.setNome("A");
		porta7.setEntrada(4);
		porta7.setSaida(4);
		porta7.setTrancada(1);
		sala4.getPortas().add(porta7);
		porta8.setNome("B");
		porta8.setEntrada(4);
		porta8.setSaida(5);
		porta8.setTrancada(0);
		sala4.getPortas().add(porta8);
		gold4.setRandomOuro(2, 5);
		sala4.getItens().add(gold4);
		diamante4.setRandomDiamante(2,5);
		sala4.getItens().add(diamante4);
		pocao4.setRandomPocao(0, 1);
		sala4.getItens().add(pocao4);
		chave4.setChave(0);
		sala4.getItens().add(chave4);
		machado4.setRandomMachado(0, 1);
		sala4.getItens().add(machado4);
		listasala.add(3, sala4);

		sala5.setNome(5);
		porta9.setNome("A");
		porta9.setEntrada(5);
		porta9.setSaida(10);
		porta9.setTrancada(0);
		sala5.getPortas().add(porta9);
		porta10.setNome("B");
		porta10.setEntrada(5);
		porta10.setSaida(4);
		porta10.setTrancada(0);
		sala5.getPortas().add(porta10);
		gold5.setRandomOuro(2, 5);
		sala5.getItens().add(gold5);
		diamante5.setRandomDiamante(2,5);
		sala5.getItens().add(diamante5);
		pocao5.setRandomPocao(0, 1);
		sala5.getItens().add(pocao5);
		chave5.setChave(0);
		sala5.getItens().add(chave5);
		machado5.setRandomMachado(0, 1);
		sala5.getItens().add(machado5);
		listasala.add(4, sala5);

		sala6.setNome(6);
		porta11.setNome("A");
		porta11.setEntrada(6);
		porta11.setSaida(1);
		porta11.setTrancada(0);
		sala6.getPortas().add(porta11);
		porta12.setNome("B");
		porta12.setEntrada(6);
		porta12.setSaida(7);
		porta12.setTrancada(0);
		sala6.getPortas().add(porta12);
		gold6.setRandomOuro(2, 5);
		sala6.getItens().add(gold6);
		diamante6.setRandomDiamante(2,5);
		sala6.getItens().add(diamante6);
		pocao6.setRandomPocao(0, 1);
		sala6.getItens().add(pocao6);
		chave6.setChave(1);
		sala6.getItens().add(chave6);
		machado6.setRandomMachado(0, 1);
		sala6.getItens().add(machado6);
		listasala.add(5, sala6);

		sala7.setNome(7);
		porta13.setNome("A");
		porta13.setEntrada(7);
		porta13.setSaida(12);
		porta13.setTrancada(1);
		sala7.getPortas().add(porta13);
		porta14.setNome("B");
		porta14.setEntrada(7);
		porta14.setSaida(6);
		porta14.setTrancada(0);
		sala7.getPortas().add(porta14);
		gold7.setRandomOuro(2, 5);
		sala7.getItens().add(gold7);
		diamante7.setRandomDiamante(2,5);
		sala7.getItens().add(diamante7);
		pocao7.setRandomPocao(0, 1);
		sala7.getItens().add(pocao7);
		chave7.setChave(0);
		sala7.getItens().add(chave7);
		machado7.setRandomMachado(0, 1);
		sala7.getItens().add(machado7);
		listasala.add(6, sala7);

		sala8.setNome(8);
		porta15.setNome("A");
		porta15.setEntrada(8);
		porta15.setSaida(13);
		porta15.setTrancada(0);
		sala8.getPortas().add(porta15);
		porta16.setNome("B");
		porta16.setEntrada(8);
		porta16.setSaida(3);
		porta16.setTrancada(0);
		sala8.getPortas().add(porta16);
		gold8.setRandomOuro(2, 5);
		sala8.getItens().add(gold8);
		diamante8.setRandomDiamante(2,5);
		sala8.getItens().add(diamante8);
		pocao8.setRandomPocao(0, 1);
		sala8.getItens().add(pocao8);
		chave8.setChave(0);
		sala8.getItens().add(chave8);
		machado8.setRandomMachado(0, 1);
		sala8.getItens().add(machado8);
		listasala.add(7, sala8);

		sala9.setNome(9);
		porta17.setNome("A");
		porta17.setEntrada(9);
		porta17.setSaida(10);
		porta17.setTrancada(0);
		sala9.getPortas().add(porta17);
		gold9.setRandomOuro(2, 5);
		sala9.getItens().add(gold9);
		diamante9.setRandomDiamante(2,5);
		sala9.getItens().add(diamante9);
		pocao9.setRandomPocao(0, 1);
		sala9.getItens().add(pocao9);
		chave9.setChave(0);
		sala9.getItens().add(chave9);
		machado9.setRandomMachado(0, 1);
		sala9.getItens().add(machado9);
		listasala.add(8, sala9);

		sala10.setNome(10);
		porta19.setNome("A");
		porta19.setEntrada(10);
		porta19.setSaida(9);
		porta19.setTrancada(0);
		sala10.getPortas().add(porta19);
		porta20.setNome("B");
		porta20.setEntrada(10);
		porta20.setSaida(15);
		porta20.setTrancada(0);
		sala10.getPortas().add(porta20);
		porta21.setNome("C");
		porta21.setEntrada(10);
		porta21.setSaida(5);
		porta21.setTrancada(0);
		sala10.getPortas().add(porta21);
		gold10.setRandomOuro(2, 5);
		sala10.getItens().add(gold10);
		diamante10.setRandomDiamante(2,5);
		sala10.getItens().add(diamante10);
		pocao10.setRandomPocao(0, 1);
		sala10.getItens().add(pocao10);
		chave10.setChave(0);
		sala10.getItens().add(chave10);
		machado10.setRandomMachado(0, 1);
		sala10.getItens().add(machado10);
		listasala.add(9, sala10);

		sala11.setNome(11);
		porta22.setNome("A");
		porta22.setEntrada(11);
		porta22.setSaida(12);
		porta22.setTrancada(0);
		sala11.getPortas().add(porta22);
		porta23.setNome("B");
		porta23.setEntrada(11);
		porta23.setSaida(16);
		porta23.setTrancada(0);
		sala11.getPortas().add(porta23);
		gold11.setRandomOuro(2, 5);
		sala11.getItens().add(gold11);
		diamante11.setRandomDiamante(2,5);
		sala11.getItens().add(diamante11);
		pocao11.setRandomPocao(0, 1);
		sala11.getItens().add(pocao11);
		chave11.setChave(0);
		sala11.getItens().add(chave11);
		machado11.setRandomMachado(0, 1);
		sala11.getItens().add(machado11);
		listasala.add(10, sala11);

		sala12.setNome(12);
		porta24.setNome("A");
		porta24.setEntrada(12);
		porta24.setSaida(11);
		porta24.setTrancada(0);
		sala12.getPortas().add(porta24);
		porta25.setNome("B");
		porta25.setEntrada(12);
		porta25.setSaida(7);
		porta25.setTrancada(0);
		sala12.getPortas().add(porta25);
		porta26.setNome("C");
		porta26.setEntrada(12);
		porta26.setSaida(13);
		porta26.setTrancada(0);
		sala12.getPortas().add(porta26);
		gold12.setRandomOuro(2, 5);
		sala12.getItens().add(gold12);
		diamante12.setRandomDiamante(2,5);
		sala12.getItens().add(diamante12);
		pocao12.setRandomPocao(0, 1);
		sala12.getItens().add(pocao12);
		chave12.setChave(1);
		sala12.getItens().add(chave12);
		machado12.setRandomMachado(0, 1);
		sala12.getItens().add(machado12);
		listasala.add(11, sala12);

		sala13.setNome(13);
		porta27.setNome("A");
		porta27.setEntrada(13);
		porta27.setSaida(12);
		porta27.setTrancada(0);
		sala13.getPortas().add(porta27);
		porta28.setNome("B");
		porta28.setEntrada(13);
		porta28.setSaida(8);
		porta28.setTrancada(0);
		sala13.getPortas().add(porta28);
		gold13.setRandomOuro(2, 5);
		sala13.getItens().add(gold13);
		diamante13.setRandomDiamante(2,5);
		sala13.getItens().add(diamante13);
		pocao13.setRandomPocao(0, 1);
		sala13.getItens().add(pocao13);
		chave13.setChave(0);
		sala13.getItens().add(chave13);
		machado13.setRandomMachado(0, 1);
		sala13.getItens().add(machado13);
		listasala.add(12, sala13);

		sala14.setNome(14);
		porta29.setNome("A");
		porta29.setEntrada(14);
		porta29.setSaida(15);
		porta29.setTrancada(0);
		sala14.getPortas().add(porta29);
		porta30.setNome("B");
		porta30.setEntrada(14);
		porta30.setSaida(19);
		porta30.setTrancada(0);
		sala14.getPortas().add(porta30);
		gold14.setRandomOuro(2, 5);
		sala14.getItens().add(gold14);
		diamante14.setRandomDiamante(2,5);
		sala14.getItens().add(diamante14);
		pocao14.setRandomPocao(0, 1);
		sala14.getItens().add(pocao14);
		chave14.setChave(1);
		sala14.getItens().add(chave14);
		machado14.setRandomMachado(0, 1);
		sala14.getItens().add(machado14);
		listasala.add(13, sala14);

		sala15.setNome(15);
		porta31.setNome("A");
		porta31.setEntrada(15);
		porta31.setSaida(14);
		porta31.setTrancada(0);
		sala15.getPortas().add(porta31);
		porta32.setNome("B");
		porta32.setEntrada(15);
		porta32.setSaida(10);
		porta32.setTrancada(0);
		sala15.getPortas().add(porta32);
		porta33.setNome("C");
		porta33.setEntrada(15);
		porta33.setSaida(20);
		porta33.setTrancada(0);
		sala15.getPortas().add(porta33);
		gold15.setRandomOuro(2, 5);
		sala15.getItens().add(gold15);
		diamante15.setRandomDiamante(2,5);
		sala15.getItens().add(diamante15);
		pocao15.setRandomPocao(0, 1);
		sala15.getItens().add(pocao15);
		chave15.setChave(0);
		sala15.getItens().add(chave15);
		machado15.setRandomMachado(0, 1);
		sala15.getItens().add(machado15);
		listasala.add(14, sala15);

		sala16.setNome(16);
		porta34.setNome("A");
		porta34.setEntrada(16);
		porta34.setSaida(11);
		porta34.setTrancada(0);
		sala16.getPortas().add(porta34);
		porta35.setNome("B");
		porta35.setEntrada(16);
		porta35.setSaida(17);
		porta35.setTrancada(0);
		sala16.getPortas().add(porta35);
		gold16.setRandomOuro(2, 5);
		sala16.getItens().add(gold16);
		diamante16.setRandomDiamante(2,5);
		sala16.getItens().add(diamante16);
		pocao16.setRandomPocao(0, 1);
		sala16.getItens().add(pocao16);
		chave16.setChave(0);
		sala16.getItens().add(chave16);
		machado16.setRandomMachado(0, 1);
		sala16.getItens().add(machado16);
		listasala.add(15, sala16);

		sala17.setNome(17);
		porta36.setNome("A");
		porta36.setEntrada(17);
		porta36.setSaida(16);
		porta36.setTrancada(0);
		sala17.getPortas().add(porta36);
		porta37.setNome("B");
		porta37.setEntrada(17);
		porta37.setSaida(18);
		porta37.setTrancada(1);
		sala17.getPortas().add(porta37);
		gold17.setRandomOuro(2, 5);
		sala17.getItens().add(gold17);
		diamante17.setRandomDiamante(2,5);
		sala17.getItens().add(diamante17);
		pocao17.setRandomPocao(0, 1);
		sala17.getItens().add(pocao17);
		chave17.setChave(0);
		sala17.getItens().add(chave17);
		machado17.setRandomMachado(0, 1);
		sala17.getItens().add(machado17);
		listasala.add(16, sala17);

		sala18.setNome(18);
		porta38.setNome("A");
		porta38.setEntrada(18);
		porta38.setSaida(19);
		porta38.setTrancada(0);
		sala18.getPortas().add(porta38);
		porta39.setNome("B");
		porta39.setEntrada(18);
		porta39.setSaida(17);
		porta39.setTrancada(0);
		sala18.getPortas().add(porta39);
		gold18.setRandomOuro(2, 5);
		sala18.getItens().add(gold18);
		diamante18.setRandomDiamante(2,5);
		sala18.getItens().add(diamante18);
		pocao18.setRandomPocao(0, 1);
		sala18.getItens().add(pocao18);
		chave18.setChave(0);
		sala18.getItens().add(chave18);
		machado18.setRandomMachado(0, 1);
		sala18.getItens().add(machado18);
		listasala.add(17, sala18);

		sala19.setNome(19);
		porta40.setNome("A");
		porta40.setEntrada(19);
		porta40.setSaida(14);
		porta40.setTrancada(0);
		sala19.getPortas().add(porta40);
		porta41.setNome("B");
		porta41.setEntrada(19);
		porta41.setSaida(18);
		porta41.setTrancada(0);
		sala19.getPortas().add(porta41);
		gold19.setRandomOuro(2, 5);
		sala19.getItens().add(gold19);
		diamante19.setRandomDiamante(2,5);
		sala19.getItens().add(diamante19);
		pocao19.setRandomPocao(0, 1);
		sala19.getItens().add(pocao19);
		chave19.setChave(0);
		sala19.getItens().add(chave19);
		machado19.setRandomMachado(0, 1);
		sala19.getItens().add(machado19);
		listasala.add(18, sala19);

		sala20.setNome(20);
		porta42.setNome("A");
		porta42.setEntrada(20);
		porta42.setSaida(15);
		porta42.setTrancada(0);
		sala20.getPortas().add(porta42);
		gold20.setRandomOuro(2, 5);
		sala20.getItens().add(gold20);
		diamante20.setRandomDiamante(2,5);
		sala20.getItens().add(diamante20);
		pocao20.setRandomPocao(0,1);
		sala20.getItens().add(pocao20);
		chave20.setChave(0);
		sala20.getItens().add(chave20);
		machado20.setRandomMachado(0, 1);
		sala20.getItens().add(machado20);
		listasala.add(19, sala20);

	}

	/*
	 * Método randomTroll: esse método tem como objetivo adicionar os troll randomicamente nas salas junto com seu nome.
	 * 
	 */
	
	public void RandomTroll(int min, int max, ArrayList<Troll> listatroll) {

		Random rand = new Random();
		Troll troll = new Troll();
		int randomTroll = rand.nextInt((max - min) + 1) + min;
		troll.setSalaTroll(randomTroll);
		troll.setNome("Florzinha");
		listatroll.add(0, troll);

		Troll troll2 = new Troll();
		int randomTroll2 = rand.nextInt((max - min) + 1) + min;
		troll2.setSalaTroll(randomTroll2);
		troll2.setNome("Lindinha");
		listatroll.add(1, troll2);

		Troll troll3 = new Troll();
		int randomTroll3 = rand.nextInt((max - min) + 1) + min;
		troll3.setSalaTroll(randomTroll3);
		troll3.setNome("Docinho");
		listatroll.add(2, troll3);

	}

}